### ISSUE TITLE
Filter doesn't work with Kind queries

### ISSUE THREAD

**Issue by husayt** [stickfigure/objectify#15]
There is a problem with filtering *.kind* queries

```
final com.googlecode.objectify.Key<?> agencyKey = ofy().load()
        .kind("MyEntity")
        .filter("my_field", ns)
```
I get exception, because class is null for *Kind* queries in LoadTypeImpl

```
java.lang.NullPointerException
	at com.googlecode.objectify.impl.QueryImpl.<init>(QueryImpl.java:69)
	at com.googlecode.objectify.impl.LoadTypeImpl.createQuery(LoadTypeImpl.java:52)
	at com.googlecode.objectify.impl.LoadTypeImpl.filter(LoadTypeImpl.java:60)
```
the problem comes to this line (QueryImpl.java:69):

```
	Subclass sub = clazz.getAnnotation(Subclass.class);
```
which should be in if block, as `clazz` is null for *kind* queries

**Comment by stickfigure** [comment]
This has been fixed in master since Jan 13. I'll interpret this as a request for a new release :)

**Comment by husayt** [comment]
Yes indeed. I was surprised to  get this bug, as I was pretty sure you fixed it. Now it is clear, I see the commit, but it did not make it to release. 

New release will be highly appreciated.


Thanks
